# Generated by Django 4.2.11 on 2024-03-26 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_project_template_task_days_prior_alter_task_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='save_as_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='days_prior',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('days_prior', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='calendarapp.projecttemplate')),
            ],
        ),
    ]
