# Generated by Django 4.2.11 on 2024-04-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_project_save_as_template_alter_task_days_prior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttemplate',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
